# Generated by Django 4.0.2 on 2022-04-19 18:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank='', default='', max_length=100, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank='', default='', max_length=100, unique=True, verbose_name='Name')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CajaMenor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gastos', models.IntegerField(default=0)),
                ('saldo', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Tipo Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, default=datetime.date(2022, 4, 19), verbose_name='fecha')),
                ('nombre_usuario', models.CharField(max_length=50, verbose_name='Nombre Usuario')),
                ('detalle', models.TextField(max_length=500, verbose_name='Observacion')),
                ('valor', models.IntegerField(default=0, verbose_name='Valor')),
                ('evidence', models.ImageField(null=True, upload_to='firmas')),
                ('CajaMenor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajaMenorApp.cajamenor')),
                ('tipoServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cajaMenorApp.tiposervicio')),
            ],
        ),
    ]
