# Generated by Django 4.0.2 on 2022-04-19 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cajaMenorApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='CajaMenor',
            new_name='Caja_menor',
        ),
    ]
