# Generated by Django 4.0.2 on 2022-04-19 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cajaMenorApp', '0002_remove_user_is_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='cajaMenor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gastos', models.IntegerField(default=0)),
                ('saldo', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
