# Generated by Django 4.0.2 on 2022-04-20 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajaMenorApp', '0003_rename_caja_menor_reporte_caja_menor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='evidence',
            field=models.ImageField(blank=True, null=True, upload_to='firmas'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2022, 4, 20), verbose_name='fecha'),
        ),
    ]
